name = "Dimensions"
uuid = "80345c00-9166-4d3e-8c72-003f651600ad"
authors = ["Cole Miller"]
version = "0.1.0"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
MakieDimExt = "Makie"
PlotsDimExt = "RecipesBase"

[compat]
julia = "1.10"
Statistics = "1.10"
Unitful = "1.21"
Makie = "0.21"
RecipesBase = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
